[measurement]
sleep_after_move_s = 3.0

[logging]
csv_path = "tomography_data.csv"

[rotators.signal_qwp]
name           = "signal_qwp"
desc           = "first_qwp"
hw_address     = "/dev/ttyUSB0"
addr_hex       = "1"
offset_degrees = 22.5

[rotators.signal_hwp]
name           = "signal_hwp"
desc           = "first_hwp"
hw_address     = "/dev/ttyUSB0"
addr_hex       = "2"
offset_degrees = 88.49

[rotators.idler_qwp]
name           = "idler_qwp"
desc           = "second_qwp"
hw_address     = "/dev/ttyUSB0"
addr_hex       = "3"
offset_degrees = 201.498

[rotators.idler_hwp]
name           = "idler_hwp"
desc           = "second_hwp"
hw_address     = "/dev/ttyUSB0"
addr_hex       = "4"
offset_degrees = 46.41

[rotators.ancillary_qwp]
name           = "ancillary_qwp"
desc           = "third_qwp"
hw_address     = "/dev/ttyUSB0"
addr_hex       = "5"
offset_degrees = 129.5

[powermeters.h]
name       = "h_power"
desc       = "h_power_meter"
hw_address = "/dev/usbtmc0"

[powermeters.v]
name       = "v_power"
desc       = "v_power_meter"
hw_address = "/dev/usbtmc1"

